### ISSUE TITLE
Multiple caches?

### ISSUE THREAD

**Issue by YuriGor** [juodumas/node-persistent-json-cache#2]
Hi, thank you for lib, exactly what I need! :+1: 

A little question:
```js
async function main() {
    const persistent = require('persistent-json-cache')
```
Any reason to require inside the function?
Is it safe to require it once on the top of my module and then create multiple cache instances loaded from separate files?
For me seems working fine, but maybe you know some caveats?

**Comment by juodumas** [comment]
No particular reason. Require is without side effects, you can use multiple caches.
